export {default as IconExplore} from'./iconExplore'
export {default as IconPlay} from './iconPlay'
export {default as Iconcomment} from './IconComment'
export {default as IconMember} from './IconMember'
export {default as IconHome} from './IconHome'
export {default as IconClock} from './IconClock'
export {default as IconEye} from './IconEye'
export {default as IconAdd} from './IconAdd'
export {default as IconDelete} from './IconDelete'
export {default as IconStar} from './IconStar'
export {default as IconEdit} from './IconEdit'
export {default as IconRight} from './IconRight'
export {default as IconLeft} from './IconLeft'
export {default as IconSideBar} from './IconSideBar'
export {default as IconSearch} from './IconSearch'
export {default as IconCheck} from './IconCheck'
export {default as IconCancel} from './IconCancel'
export {default as IconBin} from './IconBin'


